### ISSUE TITLE
exceptions.AttributeError in rdpy-rdpmitm.py

### ISSUE THREAD

**Issue by adepasquale** [citronneur/rdpy#16]
Tested freerdp version 1.2.0_beta1_pre20141115 against rdpmitm, here's the output:

```
% ./rdpy-rdpmitm.py -o /tmp 192.168.56.3
Unhandled Error
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 209, in dataReceived
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/tpkt.py", line 195, in readData
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 147, in recvData
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/mcs.py", line 520, in recvConnectInitial
    
exceptions.AttributeError: 'NoneType' object has no attribute 'channelDefArray'
```

**Comment by adepasquale** [comment]
I haven't tried latest master commits on https://github.com/FreeRDP/FreeRDP, should I?

**Comment by citronneur** [comment]
Very strange bug... Please can you give me the link to 1.2.0_beta1_pre20141115?

**Comment by citronneur** [comment]
Can you try last commit on hotfix branch?

**Comment by adepasquale** [comment]
Sure, here it is:

https://github.com/FreeRDP/FreeRDP/archive/7a6c6b7436c2fcb02a38bf89e0b3efcdb43f2ef5.tar.gz
https://github.com/FreeRDP/FreeRDP/commit/7a6c6b7436c2fcb02a38bf89e0b3efcdb43f2ef5

**Comment by adepasquale** [comment]
I have pulled your latest commit e9db7d720f6ee3c9b87d3a1228b3deda0dd1f11c, now only freerdp prints an error message (rdpmitm prints nothing):

```
% xfreerdp /v:127.0.0.1 /u:username /p:password       
[15:28:20:146] [25336:-1147242752] [ERROR][com.freerdp.core] - gcc_read_conference_create_response failed
[15:28:20:146] [25336:-1147242752] [ERROR][com.freerdp.core.connection] - rdp_client_connect_mcs_connect_response: mcs_recv_connect_response failed
[15:28:20:146] [25336:-1147242752] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x2000D
```
But if I connect straight to the RDP server, it works:
```
% xfreerdp /v:192.168.56.3 /u:username /p:password
[15:30:23:380] [27094:1944729344] [INFO][com.freerdp.client.x11] - Closed from X11
```

**Comment by citronneur** [comment]
i try with 1.0.1 version (default on ubuntu) and works fine...

**Comment by citronneur** [comment]
work with 1.0.2 verion too.

**Comment by citronneur** [comment]
Ok i fix issue for freerdp last version on last commit on hotfix branch. But works only when mitm use ssl as security layer. I open a new issue for this bug.

**Comment by adepasquale** [comment]
Thanks, I confirm that now FreeRDP works but rdpy-mitm does not save session.
